//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterOrders
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderId { get; set; }
        public int StockId { get; set; }
        public Nullable<int> UserId { get; set; }
        public decimal UnitPrice { get; set; }
        public short Quantity { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Stocks Stocks { get; set; }
    }
}
